In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
VGSales_file = "VGsales_Clean.csv"
VGS = pd.read_csv(VGSales_file)
VGS.head(1000000)

,Unnamed: 0,Name,Platform,Year,Publisher,NA_Sales,Company
0,0,Wii Sports,Wii,2006.0,Nintendo,41.49,Nintendo
1,2,Mario Kart Wii,Wii,2008.0,Nintendo,15.85,Nintendo
2,3,Wii Sports Resort,Wii,2009.0,Nintendo,15.75,Nintendo
3,6,New Super Mario Bros.,DS,2006.0,Nintendo,11.38,Nintendo
4,7,Wii Play,Wii,2006.0,Nintendo,14.03,Nintendo
...,...,...,...,...,...,...,...
15332,16593,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Kemco,0.01,Nintendo
15333,16594,Men in Black II: Alien Escape,GC,2003.0,Infogrames,0.01,Nintendo
15334,16595,SCORE International Baja 1000: The Official Game,PS2,2008.0,Activision,0.00,SONY
15335,16596,Know How 2,DS,2010.0,7G//AMES,0.00,Nintendo
15336,16597,Spirits & Spells,GBA,2003.0,Wanadoo,0.01,Nintendo

In [6]:
MSScore_file = "new_metacritic_df.csv"
MSS = pd.read_csv(MSScore_file)
MSS.head(100000)

,Unnamed: 0,Name,Platform,Publisher,release_date,metascore,user_score,Company,Year
0,29,GoldenEye 007,N64,Nintendo,"Aug 25, 1997",96,9.0,Nintendo,1997
1,30,Castlevania: Symphony of the Night,PS,Konami,"Oct 2, 1997",93,9.2,Sony,1997
2,31,Sid Meier's Gettysburg!,PC,Electronic Arts,"Sep 30, 1997",92,7.4,Other,1997
3,32,Final Fantasy VII,PS,SCEA,"Sep 3, 1997",92,9.2,Sony,1997
4,33,PaRappa the Rapper,PS,SCEA,"Oct 31, 1997",92,7.5,Sony,1997
...,...,...,...,...,...,...,...,...,...
18670,18701,Sniper Rust VR,PC,Zatun Game Studio,"Dec 26, 2017",29,tbd,Other,2017
18671,18702,Woodle Tree Adventures Deluxe,Switch,Chubby Pixel,"Dec 21, 2017",28,5.1,Nintendo,2017
18672,18703,Troll and I,PC,Maximum Games,"Mar 21, 2017",27,3.8,Other,2017
18673,18704,Road Rage,PS4,Maximum Games,"Nov 14, 2017",26,2.2,Sony,2017
18674,18705,Vroom in the Night Sky,Switch,Poisoft,"Apr 5, 2017",17,3.1,Nintendo,2017

In [11]:
df = pd.merge(VGS, MSS, on = ['Name', 'Platform', 'Year'])
df.head(100000)

,Unnamed: 0_x,Name,Platform,Year,Publisher_x,NA_Sales,Company_x,Unnamed: 0_y,Publisher_y,release_date,metascore,user_score,Company_y
0,6,New Super Mario Bros.,DS,2006.0,Nintendo,11.38,Nintendo,4864,Nintendo,"May 15, 2006",89,8.5,Nintendo
1,11,Mario Kart DS,DS,2005.0,Nintendo,9.81,Nintendo,3893,Nintendo,"Nov 14, 2005",91,8.7,Nintendo
2,15,Kinect Adventures!,X360,2010.0,Microsoft Game Studios,14.97,Microsoft,10026,Microsoft Game Studios,"Nov 4, 2010",61,6.3,Microsoft
3,16,Grand Theft Auto V,PS3,2013.0,Take-Two Interactive,7.01,SONY,12398,Rockstar Games,"Sep 17, 2013",97,8.3,Sony
4,17,Grand Theft Auto: San Andreas,PS2,2004.0,Take-Two Interactive,9.43,SONY,3064,Rockstar Games,"Oct 26, 2004",95,9.0,Sony
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5228,16579,PGA European Tour,N64,2000.0,Infogrames,0.01,Nintendo,496,Infogrames,"Jun 15, 2000",58,8.0,Nintendo
5229,16582,Planet Monsters,GBA,2001.0,Titus,0.01,Nintendo,965,Titus Software,"Dec 6, 2001",67,tbd,Nintendo
5230,16584,Bust-A-Move 3000,GC,2003.0,Ubisoft,0.01,Nintendo,2948,Ubisoft,"Feb 12, 2003",53,tbd,Nintendo
5231,16585,Breach,PC,2011.0,Destineer,0.01,Microsoft,11066,Atomic Games,"Jan 26, 2011",61,5.7,Other
5232,16588,Mega Brain Boost,DS,2008.0,Majesco Entertainment,0.01,Nintendo,7894,Majesco Games,"Jan 22, 2008",48,tbd,Nintendo